version: "3"

services:
  mongodb:
    image: mongo:latest

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb
    command: npm start
    depends_on:
      - mongodb
    volumes:
      - ".:/usr/app"
